# Generated by Django 4.2.20 on 2025-08-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gener',
            field=models.CharField(choices=[('None', 'None'), ('AI', 'Ai'), ('Graphic design', 'Graphic'), ('Programming Language', 'Programming'), ('Language', 'Language'), ('Sale & Marketing', 'Sales'), ('Data Science & Analytics', 'Data Science')], default='None', max_length=50),
        ),
    ]
