# Generated by Django 4.2.20 on 2025-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_gener'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.URLField(default='https://www.youtube.com/watch?v=2PuFyjAs7JA&pp=ygUKdGVzdCB2aWRlbw%3D%3D', max_length=600),
        ),
    ]
